id: P004343
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD95809
  title: རྒྱུད་བླ་ས་འགྲེལ
  author: ''
  volumes:
    343c0cb2eae745848ffcccb1b33cb514:
      image_group_id: I1PD95836
      title: ''
      volume_number: 1
      total_pages: 394
      base_file: v001.txt
